services:
  - type: web
    name: resume-matcher
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd frontend
      npm install
      npm run build
      cd ..
      mkdir -p backend/app/static
      rm -rf backend/app/static/*
      cp -r frontend/dist/* backend/app/static/
    startCommand: gunicorn backend.app.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
