services:
  - type: web
    name: resume-matcher
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd frontend
      npm install
      npm run build
      cd ..
      mkdir -p backend/app/static
      cp -r frontend/dist/* backend/app/static/
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
